version: '3.8'

services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    ports:
      - "23232:23232"  # AMQP
      - "23233:23233"  # Management Console
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:23232//

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "27272:8000"
    depends_on:
      - celery
