version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//
      # 필요한 경우 Hugging Face 토큰을 설정
      - HF_AUTH_TOKEN=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
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    depends_on:
      - rabbitmq

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    runtime: nvidia
    ports:
      - "27272:8000"
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//
      # 필요한 경우 Hugging Face 토큰을 설정
      - HF_AUTH_TOKEN=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
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    depends_on:
      - rabbitmq
      - celery_worker
