# Python 3.10 이미지를 기반으로 함
FROM python:3.10-slim

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 패키지 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 애플리케이션 파일 복사
COPY . .
COPY main.py .
COPY celery_worker.py .

# Celery 워커 실행 명령어
CMD ["celery", "-A", "celery_worker", "worker", "--loglevel=info", "--pool=solo"]

