version: '3.8'

services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile.celery  # 위에서 만든 Dockerfile을 사용
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - CELERY_BROKER_URL=amqp://user:password@localhost:5672//
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
      - CUDA_LAUNCH_BLOCKING=1
    ports:
      - "27272:8000"  # FastAPI 포트
    depends_on:
      rabbitmq:
        condition: service_healthy  # RabbitMQ가 준비될 때까지 대기
    network_mode: "host"  # 호스트 네트워크 모드 사용 (가상 네트워크 문제 완화)

  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
