version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
      - CUDA_LAUNCH_BLOCKING=1
      - CELERYD_LOG_LEVEL=DEBUG
    depends_on:
      - rabbitmq

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "27272:8000"
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//
    depends_on:
      - rabbitmq
      - celery_worker
