name: Deploy to Amazon Lightsail

on:
  push:
    branches: [ "main" ]  # main 브랜치에 푸시될 때 워크플로우가 실행됩니다.

env:
  AWS_REGION: us-east-1
  LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Build, tag, and push image to Amazon ECR Public
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: d0v2k3o3  # 본인의 alias 입력
          REPOSITORY: ohmyservice_ai  # repository명 설정
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # docker-compose를 사용하여 이미지 빌드
          docker-compose -f docker-compose.yml build --no-cache

          docker tag ai_web_app:latest $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:web_app-$IMAGE_TAG
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:web_app-$IMAGE_TAG
          
          echo "web_app_image=$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:web_app-$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Install SSH and sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass

      - name: Verify Environment Variables
        run: |
          echo "LIGHTSAIL_INSTANCE_IP: $LIGHTSAIL_INSTANCE_IP"
          echo "SSH_USERNAME: $SSH_USERNAME"
          #echo "CELERY_IMAGE: ${{ steps.build-image.outputs.celery_image }}"
          #echo "FASTAPI_IMAGE: ${{ steps.build-image.outputs.fastapi_image }}"

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy necessary files to Lightsail
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa docker-compose.yml $SSH_USERNAME@$LIGHTSAIL_INSTANCE_IP:~/docker-compose.yml
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa Dockerfile.celery $SSH_USERNAME@$LIGHTSAIL_INSTANCE_IP:~/Dockerfile.celery
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa requirements.txt $SSH_USERNAME@$LIGHTSAIL_INSTANCE_IP:~/requirements.txt
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa celery_worker.py $SSH_USERNAME@$LIGHTSAIL_INSTANCE_IP:~/celery_worker.py
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa main.py $SSH_USERNAME@$LIGHTSAIL_INSTANCE_IP:~/main.py

      - name: Deploy to Amazon Lightsail using Docker Compose
        env:
          WEB_APP_IMAGEL: ${{ steps.build-image.outputs.web_app_image }}
        run: |
          echo "Deploying to Lightsail: $LIGHTSAIL_INSTANCE_IP"

          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$LIGHTSAIL_INSTANCE_IP << EOF
            
            # docker-compose.yml 파일을 사용하여 배포
            docker-compose down
            docker-compose pull
            docker-compose up -d
          EOF
