name: Deploy FastAPI, Celery, and RabbitMQ to Amazon Lightsail

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: Build, tag, and push FastAPI image to Amazon ECR Public
      id: build-fastapi-image
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: d0v2k3o3
        REPOSITORY: ohmyservice_ai
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --no-cache -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:fastapi-$IMAGE_TAG -f Dockerfile.fastapi .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:fastapi-$IMAGE_TAG
        echo "fastapi_image=$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:fastapi-$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build, tag, and push Celery image to Amazon ECR Public
      id: build-celery-image
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: d0v2k3o3
        REPOSITORY: ohmyservice_ai
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --no-cache -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:celery-$IMAGE_TAG -f Dockerfile.celery .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:celery-$IMAGE_TAG
        echo "celery_image=$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:celery-$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Copy SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy .env file to Lightsail instance
      run: |
        scp -o StrictHostKeyChecking=no .env $SSH_USERNAME@$LIGHTSAIL_INSTANCE_IP:/home/$SSH_USERNAME/.env

    - name: Deploy to Amazon Lightsail
      env:
        FASTAPI_IMAGE: ${{ steps.build-fastapi-image.outputs.fastapi_image }}
        CELERY_IMAGE: ${{ steps.build-celery-image.outputs.celery_image }}
        RABBITMQ_IMAGE: rabbitmq:management
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$LIGHTSAIL_INSTANCE_IP << EOF
          FASTAPI_IMAGE=${FASTAPI_IMAGE}
          CELERY_IMAGE=${CELERY_IMAGE}
          RABBITMQ_IMAGE=${RABBITMQ_IMAGE}
          
          # Pull the images
          sudo docker pull \\$FASTAPI_IMAGE
          sudo docker pull \\$CELERY_IMAGE
          sudo docker pull \\$RABBITMQ_IMAGE
          
          # Stop and remove existing containers
          sudo docker stop fastapi_app || true
          sudo docker rm fastapi_app || true
          sudo docker stop celery_worker || true
          sudo docker rm celery_worker || true
          sudo docker stop rabbitmq || true
          sudo docker rm rabbitmq || true
          
          # Run new containers
          sudo docker run -d --name fastapi_app --env-file /home/$SSH_USERNAME/.env -p 28282:8000 \\$FASTAPI_IMAGE
          sudo docker run -d --name celery_worker --env-file /home/$SSH_USERNAME/.env \\$CELERY_IMAGE
          sudo docker run -d --name rabbitmq -p 25672:15672 -p 26262:5672 \\$RABBITMQ_IMAGE
        EOF
